#dev环境  mysql7.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goview?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #linux服务器
    #url: jdbc:sqlite://home/cqfy/project/OSSDATABASE/oss.db
    username: lzf
    password: root
    ### 连接池配置
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 30
      max-wait: 40
      validation-query: SELECT 1
